// Generated by CoffeeScript 1.6.3
var Bridge, BridgeItem, Bullet, Line, Monster, Spaceship, SpaceshipLife,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Spaceship = (function(_super) {
  var delay;

  __extends(Spaceship, _super);

  function Spaceship(textures, textures2, x, y) {
    Spaceship.__super__.constructor.call(this, textures, textures2, x, y);
    this.setPosition(x, y);
    this.animationSpeed = 0.05;
    this.textures1 = textures;
    this.textures2 = textures2;
    this.defautPosX = x;
    this.defautPosY = y;
  }

  Spaceship.prototype.setPosition = function(x, y) {
    this.position.x = x;
    return this.position.y = y;
  };

  delay = function(time, fn, context) {
    return setTimeout(fn, time, context);
  };

  Spaceship.prototype.die = function() {
    this.textures = this.textures2;
    this.animationSpeed = 0.1;
    this.gotoAndPlay(0);
    return delay(1000, this.reset, this);
  };

  Spaceship.prototype.reset = function(context) {
    return context.textures = context.textures1;
  };

  return Spaceship;

})(PIXI.MovieClip);

SpaceshipLife = (function(_super) {
  __extends(SpaceshipLife, _super);

  function SpaceshipLife(texture) {
    SpaceshipLife.__super__.constructor.call(this, texture);
    this.x = this.position.x;
    this.y = this.position.y;
    this.width = this.texture.width;
    this.height = this.texture.height;
  }

  SpaceshipLife.prototype.setPosition = function(x, y) {
    this.position.x = x;
    return this.position.y = y;
  };

  return SpaceshipLife;

})(PIXI.Sprite);

Monster = (function(_super) {
  var delay;

  __extends(Monster, _super);

  function Monster(textures, textures2, points, x, y, type) {
    Monster.__super__.constructor.call(this, textures, textures2, points, x, y, type);
    this.type = type;
    this.points = points;
    this.setPosition(x, y);
    this.animationSpeed = 0.04;
    this.play();
    this.textures2 = textures2;
  }

  Monster.prototype.setPosition = function(x, y) {
    this.position.x = x;
    return this.position.y = y;
  };

  Monster.prototype.localToGlobal = function() {
    var obj;
    obj = {};
    obj.x = this.position.x + this.parent.position.x;
    obj.y = this.position.y + this.parent.position.y;
    return obj;
  };

  Monster.prototype.die = function() {
    if (this.textures2) {
      this.textures = this.textures2;
      delay(50, this.destroy, this);
    }
    if (!this.textures2) {
      return this.parent.removeChild(this);
    }
  };

  delay = function(time, fn, context) {
    return setTimeout(fn, time, context);
  };

  Monster.prototype.destroy = function(context) {
    context.parent.removeChild(context);
    return context = null;
  };

  return Monster;

})(PIXI.MovieClip);

Bullet = (function(_super) {
  __extends(Bullet, _super);

  function Bullet(texture) {
    Bullet.__super__.constructor.call(this, texture);
    this.x = this.position.x;
    this.y = this.position.y;
    this.width = this.texture.width;
    this.height = this.texture.height;
  }

  Bullet.prototype.setPosition = function(x, y) {
    this.position.x = x;
    return this.position.y = y;
  };

  return Bullet;

})(PIXI.Sprite);

Line = (function(_super) {
  __extends(Line, _super);

  function Line() {
    Line.__super__.constructor.call(this);
    this.reverse = false;
  }

  return Line;

})(PIXI.DisplayObjectContainer);

Bridge = (function(_super) {
  __extends(Bridge, _super);

  function Bridge(t1, t2, t3, t4, t5, t6, t7, t8, t9) {
    var b1, b2, b3, b4, b5, b6, b7, b8, b9;
    Bridge.__super__.constructor.call(this);
    b1 = new BridgeItem(t1);
    this.addChild(b1);
    b2 = new BridgeItem(t2);
    b2.position.x = 14;
    this.addChild(b2);
    b3 = new BridgeItem(t3);
    b3.position.x = 28;
    this.addChild(b3);
    b4 = new BridgeItem(t4);
    b4.position.y = 11;
    this.addChild(b4);
    b5 = new BridgeItem(t5);
    b5.position.x = 14;
    b5.position.y = 11;
    this.addChild(b5);
    b6 = new BridgeItem(t6);
    b6.position.x = 28;
    b6.position.y = 11;
    this.addChild(b6);
    b7 = new BridgeItem(t7);
    b7.position.x = 0;
    b7.position.y = 22;
    this.addChild(b7);
    b8 = new BridgeItem(t8);
    b8.position.x = 14;
    b8.position.y = 22;
    this.addChild(b8);
    b9 = new BridgeItem(t9);
    b9.position.x = 28;
    b9.position.y = 22;
    this.addChild(b9);
  }

  return Bridge;

})(PIXI.DisplayObjectContainer);

BridgeItem = (function(_super) {
  __extends(BridgeItem, _super);

  function BridgeItem(textures) {
    BridgeItem.__super__.constructor.call(this, textures);
    this.gotoAndStop(0);
    this.count = 0;
  }

  BridgeItem.prototype.localToGlobal = function() {
    var obj;
    obj = {};
    obj.x = this.position.x + this.parent.position.x;
    obj.y = this.position.y + this.parent.position.y;
    return obj;
  };

  BridgeItem.prototype.touch = function() {
    this.count++;
    return this.gotoAndStop(1);
  };

  return BridgeItem;

})(PIXI.MovieClip);
